person:
  name: SpringBoot
  age: 18
  brith: 1990-01-01
  maps: {key: value}
  lists:
    - wahaha
    - xixi
---
server:
  port: 8026  # prod
spring:
  profiles: prod
---
server:
  port: 18027  # beta
spring:
  profiles: beta
---
server:
  port: 8028  # release
spring:
  profiles: release